name: Fetch JetBlue Tweets

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch tweets
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: python lambda_function.py

    - name: Commit and push updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add jetblue_tweets.csv
        git commit -m "Update JetBlue tweets"
        git push
      continue-on-error: true  # Prevent failure if no new tweets
